### ISSUE TITLE
not working with or without nwh

### ISSUE THREAD

**Issue by VicPrzz00** [ATG-Simulator/VehicleNoiseSynthesizer#1]
hi, im not sure if this is still being checked on but for some reason the scripts wont work neither on a clean project nor a nwh scene, and i couldn't figure out why, i get no compiling errors, I even checked the script if there was anything that needs enabling but still nothing. Any help would be appreciated, thanks

**Comment by imDanoush** [comment]
Hi,
Happy to help. I just noticed that you sent a message here. Would you please take a screenshot of the inspector as the starting point to resolve the issue?
Alternatively, please check this image. As you can see, the audio clips should have "string"+"_" and a number, or just a number so that it could understand which RPM an audio clip is playing. Also, there is a Debug checkbox, you can enable and forcefully play the audio given the fact that the NWH Vehicle is "turned on" if you use the default scripts.
Also, make sure the audio is not muted in the Unity editor.
![image](https://www.nwhvehiclephysics.com/lib/exe/fetch.php/pasted/20230813-124247.png "screenshot")
Best.

**Comment by imDanoush** [comment]
Since no replies have been received, I marked it as closed, please reopen it if needed to resolve further related issues.

**Comment by ATG-Simulator** [comment]
A new branch is created to start working on optimizing the UI/UX experience of the plugin to avoid confusion, but it is not planned nor prioritized for the near future.

**Comment by ATG-Simulator** [comment]
The UI/UX issue has been resolved, and with [the latest UnityPackage release](https://github.com/ATG-Simulator/VehicleNoiseSynthesizer/releases/tag/1.5f), new users should no longer encounter muted audio or other issues. A functional demo scene is now included to ensure a smoother setup experience.
